# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0946e5c3ca6d8468b51aeaac0453cd8724a071284ba19a8c13e469e198d23ddf42a193725b7288d858bf4e71447b8dead0c79104c96b6464358a34dfd2acd68

test:
  secret_key_base: 56459e3e840930418f2eeb3f340f7a6230bc7bf15432d916a5650f2db8012788fe2f00768f7eb9f046c5fcd802d5e7d0ff1ef2b0bc69f72bb088888347999ce3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
